### ISSUE TITLE
运行不了 KeyError

### ISSUE THREAD

**Issue by viocha** [GDDG08/YanHeKT_Downloader#5]
```
C:\Users\vioch\Desktop\PuBeta-1.2-with.FFMPEG\main.py:1: SyntaxWarning: invalid escape sequence '\F'
  '''
C:\Users\vioch\Desktop\PuBeta-1.2-with.FFMPEG\m3u8dl.py:1: SyntaxWarning: invalid escape sequence '\O'
  '''
Traceback (most recent call last):
  File "C:\Users\vioch\Desktop\PuBeta-1.2-with.FFMPEG\main.py", line 11, in <module>
    import m3u8dl
  File "C:\Users\vioch\Desktop\PuBeta-1.2-with.FFMPEG\m3u8dl.py", line 18, in <module>
    import js2py
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
```

**Comment by AuYang261** [comment]
下载的课程编号是多少

**Comment by viocha** [comment]
https://www.yanhekt.cn/course/45497
编号：45497

**Comment by HansZ8** [comment]
hi, 请问js2py是什么版本？

**Comment by HansZ8** [comment]
初步排查是环境问题，请移步https://github.com/ZJC-GH/YanHeKT_Downloader/releases/tag/Release
尝试使用打包好的版本,测试一下

**注意该版本使用方法略有区别**
- 双击exe，直接输入课程编号
- 具体参考 https://github.com/GDDG08/YanHeKT_Downloader/tree/dev?tab=readme-ov-file#%E9%A3%9F%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by KJH-x** [comment]
这是一个依赖bug，Js2Py尚不支持Python3.12
见PiotrDabkowski/Js2Py#317

**Comment by HansZ8** [comment]
> 这是一个依赖bug，Js2Py尚不支持Python3.12 见[PiotrDabkowski/Js2Py#317](https://github.com/PiotrDabkowski/Js2Py/issues/317)

感谢！

**Comment by HansZ8** [comment]
@viocha @KJH-x 问题已修复，移除了js2py
